services:
  - type: web
    name: loupgarou-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "daphne -b 0.0.0.0 -p $PORT loupgarou.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: REDIS_URL
        fromService:
          type: redis
          name: loupgarou-redis
          property: connectionString

  - type: redis
    name: loupgarou-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
